### ISSUE TITLE
platformjs ->webcomponentsjs

### ISSUE THREAD

**Issue by felixcriv** [spirosikmd/ajax-promise#2]
Can't make this to work with webcomponentsjs.

**Comment by czellweg** [comment]
I got it to work beautifully with webcomponentjs, e.g. I've cloned the repo and installed the ajax-promise in my project with locally updated bower dependencies.

I have used those:
```json
"dependencies": {
    "polymer": "Polymer/polymer#~0.5.2",
    "core-ajax":"Polymer/core-ajax#~0.5.2"
  }
```

**Comment by spirosikmd** [comment]
It wasn't also working for me @czellweg. I will try your recommendation.

**Comment by spirosikmd** [comment]
Indeed with 0.5.2 versions of polymer and core-ajax it works. Thanks @czellweg! I will update!
